[env]
TERM = "xterm-256color"

[font]
size = 20

[scrolling]
history = 10000
multiplier = 3

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C\""
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C-"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C%"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C|"
key = "Return"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CC"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CS"
key = "N"
mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"

[keyboard.bindings.command]
args = ["msg", "create-window", "-e", "/usr/local/bin/fish", "--login", "--command", "tmux-sessions --all"]
program = "/usr/local/bin/alacritty"

[[keyboard.bindings]]
chars = "\u001Cx"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C&"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cd"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C[/"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C[?"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CG"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CA"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CR"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CE"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CO"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cz"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CX"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:wa
"""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Ch"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ck"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ch"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cj"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ck"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cl"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CH"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CJ"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CK"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CL"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CH"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CJ"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CK"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CL"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C^"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C!"
key = "B"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B1"
key = "Key1"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B2"
key = "Key2"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B3"
key = "Key3"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B4"
key = "Key4"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B5"
key = "Key5"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B6"
key = "Key6"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B7"
key = "Key7"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B8"
key = "Key8"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B9"
key = "Key9"
mods = "Command|Shift"

[shell]
args = ["--login", "--command", "/opt/homebrew/bin/tmux new-session -A -D -s main"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
startup_mode = "SimpleFullscreen"
opacity = 0.8
